[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router", "web"] }
ui = { workspace = true }
wasm-bindgen = "0.2"
web-sys = "0.3"

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "ui/server"]
