[package]
name = "api-main"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6.6", features = ["d1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jwt-simple = { version = "0.12", default-features = false, features = ["pure-rust"] }
base64 = "0.22"
serde_urlencoded = "0.7"
js-sys = "0.3"
anyhow = "1"
url = "2.5"
argon2 = { version = "0.5", default-features = false, features = ["password-hash", "alloc"] }
getrandom = { version = "0.2", features = ["js"] }

