[package]
name = "api-gmail-scanner"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6.6", features = ["d1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jwt-simple = { version = "0.12", default-features = false, features = ["pure-rust"] }
anyhow = "1"
url = "2.5"
chrono = { version = "0.4", features = ["serde"] }
serde_urlencoded = "0.7"
getrandom = { version = "0.2", features = ["js"] }
base64 = { version = "0.22", features = ["alloc"] }

